import Head from "next/head";

import DraggableSprites from "@/components/DraggableSprites";
import ListOfSprites from "@/components/ListOfSprites";

import { Flex, Heading } from "@chakra-ui/react";
import { ConnectButton } from "@rainbow-me/rainbowkit";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zen Garden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex margin="3% 0" justify="space-evenly">
          <Heading>Zen Garden</Heading>
          <ConnectButton />
        </Flex>
        <Flex direction="row" justify="space-around" align="center">
          <DraggableSprites />
          <ListOfSprites />
        </Flex>
      </main>
    </>
  );
}
